---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hbase-operator-clusterrole
rules:
  # For Apache ZooKeeper dependents
  - apiGroups:
      - zookeeper.stackable.tech
    resources:
      - zookeeperclusters
    verbs:
      - get
      - list
      - watch
  # For Apache HDFS dependents
  - apiGroups:
      - hdfs.stackable.tech
    resources:
      - hdfsclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
    verbs:
      - create
      - delete
      - list
      - watch
      - update
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - command.hbase.stackable.tech
    resources:
      - inits
      - restarts
      - starts
      - stops
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - command.hbase.stackable.tech
    resources:
      - inits/status
    verbs:
      - patch
  - apiGroups:
      - hbase.stackable.tech
    resources:
      - hbaseclusters
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - hbase.stackable.tech
    resources:
      - hbaseclusters/status
    verbs:
      - patch
