[workspace]
members = ["rust/crd", "rust/operator-binary"]
resolver = "2"

[workspace.package]
version = "0.0.0-dev"
authors = ["Stackable GmbH <info@stackable.tech>"]
license = "OSL-3.0"
edition = "2021"
repository = "https://github.com/stackabletech/hbase-operator"

[workspace.dependencies]
anyhow = "1.0"
built = { version = "0.7", features = ["chrono", "git2"] }
clap = "4.3"
fnv = "1.0"
futures = { version = "0.3", features = ["compat"] }
indoc = "2.0"
rstest = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
snafu = "0.7"
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.60.1" }
product-config = { git = "https://github.com/stackabletech/product-config.git", tag = "0.6.0" }
strum = { version = "0.25", features = ["derive"] }
tokio = { version = "1.29", features = ["full"] }
tracing = "0.1"

[patch.crates-io]
# We need this override, because built in version 0.7 onwards doesn't have a config setting to
# suppress writing the environment anymore.
# This breaks our Tilt workflow with the following error:
#   `Missing expected environment variable "CARGO_PKG_LICENSE"`
# We patch this dependency with a fork which removes this feature and have openend an issue upstream:
# https://github.com/lukaslueg/built/issues/62
built = { git = "https://github.com/stackabletech/built.git", branch = "feat/skip-environment", features = ["chrono", "git2", "skip-environment"] }

# [patch."https://github.com/stackabletech/operator-rs.git"]
# stackable-operator = { git = "https://github.com/stackabletech//operator-rs.git", branch = "main" }
