---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: aws-eks
metadata:
  name: hbase-operator-integration-tests
  description: "Cluster for HBase Operator Integration Tests (AWS EKS)"
publicKeys: []
spec:
  region: "eu-central-1"
  awsInstanceType: "t2.medium"
  versions:
    _-operator: NIGHTLY
    hbase-operator: "$HBASE_OPERATOR_VERSION"
  node_count: 3
