:clusterName: \{clusterName\}
:namespace: \{namespace\}

= Discovery

The Stackable Operator for Apache HBase publishes a discovery https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#configmap-v1-core[`ConfigMap`], which exposes a client configuration bundle that allows access to the Apache HBase cluster.

== Example

Given the following HBase cluster:

[source,yaml,subs="normal,callouts"]
----
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: {clusterName} # <1>
  namespace: {namespace} # <2>
spec:
  hdfsConfigMapName: {hdfs-cluster-name} #<3>
  zookeeperConfigMapName: {zookeeper-znode-name} #<4>
  config:
    hbaseRootdir: /hbase
----
<1> The name of the HBase cluster, which is also the name of the created discovery `ConfigMap`.
<2> The namespace of the discovery `ConfigMap`.
<3> The `ConfigMap` name to discover the HDFS cluster.
<4> The `ConfigMap` name to discover the ZooKeeper cluster.

The resulting discovery `ConfigMap` is located at `{namespace}/{clusterName}`.

== Contents

The `ConfigMap` data values are formatted as Hadoop XML files which allows simple mounting of that `ConfigMap` into pods that require access to HBase.

`hbase-site.xml`::
Contains the `hbase.zookeeper.quorum` property.
