= Installation

There are three ways to run the HBase Operator:

1. Helm managed Docker container deployment on Kubernetes

2. As a Docker container

3. Build from source.

== Helm

Helm allows you to download and deploy Stackable operators on Kubernetes and is by far the easiest
installation method. First ensure that you have installed the Stackable Operators Helm repository:
[source,bash]
----
$ helm repo add stackable https://repo.stackable.tech/repository/helm-stable/
----

Then install the Stackable Operator for Apache HBase
[source,bash]
----
$ helm install hbase-operator stackable/hbase-operator
----

Helm will deploy the operator in a Kubernetes container and apply the CRDs for the Apache HBase
service. You are now ready to deploy Apache HBase in Kubernetes.

== Docker

This Operator is published as a Docker image:

[source]
----
docker.stackable.tech/stackable/hbase-operator
----

When installing manually with Docker you will need to install the Stackable CRDs for Apache HBase
in your Kubernetes environment. These are available on the
https://github.com/stackabletech/hbase-operator/tree/main/deploy/crd[Stackable GitHub repository]
for this operator.
[source]
----
$ kubectl apply -f hbasecluster.crd.yaml
----

To run it straight from Docker you can use this command:
[source,bash]
----
docker run \
    --name hbase-operator \
    --network host \
    --env KUBECONFIG=/home/stackable/.kube/config \
    --mount type=bind,source="$HOME/.kube/config",target="/home/stackable/.kube/config" \
    docker.stackable.tech/stackable/hbase-operator:latest
----

== Building the operator from source

This operator is written in Rust and is developed against the latest stable Rust release (1.58 at
the time of writing).

[source]
----
cargo run -- crd | kubectl apply -f -
cargo run -- run
----
