= Usage

== Requirements

A distributed Apache HBase installation depends on a running Apache ZooKeeper and HDFS cluster. See
the documentation for the https://docs.stackable.tech/hdfs/usage.html[Stackable Operator for Apache HDFS]
how to set up these clusters.

== Deployment of an Apache HBase cluster

An Apache HBase cluster can be created with the following cluster specification:

[source,yaml]
----
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: simple-hbase
spec:
  version: 2.4.11
  config:
    hdfsConfigMapName: simple-hdfs-namenode-default
    zookeeperConfigMapName: simple-hbase-znode
    hbaseManagesZk: false
    hbaseOpts:
    hbaseClusterDistributed: true
    hbaseRootdir: hdfs://simple-hdfs/hbase
  masters:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
  regionServers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
  restServers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-hbase-znode
spec:
  clusterRef:
    name: simple-zk
----

`hdfsConfigMapName` references the config map created by the Stackable HDFS operator.

`zookeeperConfigMapName` references the config map created by the Stackable ZooKeeper operator.

`hbaseManagesZk` is mapped to the environment variable `HBASE_MANAGES_ZK` in `hbase-env.sh`.

`hbaseOpts` is mapped to the environment variable `HBASE_OPTS` in `hbase-env.sh`.

`hbaseClusterDistributed` is mapped to `hbase.cluster.distributed` in `hbase-site.xml`.

`hbaseRootdir` is mapped to `hbase.rootdir` in `hbase-site.xml`.

== Monitoring

The managed HBase instances are automatically configured to export Prometheus metrics. See
xref:home::monitoring.adoc[] for more details.

== Configuration Overrides

The cluster definition also supports overriding configuration properties and environment variables, either per role or per role group, where the more specific override (role group) has precedence over the less specific one (role).

IMPORTANT: Overriding certain properties which are set by operator can interfere with the operator and can lead to problems.

=== Configuration Properties

For a role or role group, at the same level of `config`, you can specify: `configOverrides` for the following files:

- `hbase-site.xml`
- `hbase-env.sh`

// hdfs-site.xml is not listed here. The file is always taken from the referenced hdfs cluster

For example, if you want to set the `hbase.rest.threads.min` to 4 and the `HBASE_HEAPSIZE` to two GB adapt the `restServers` section of the cluster resource like so:

[source,yaml]
----
restServers:
  roleGroups:
    default:
      config: {}
      configOverrides:
        hbase-site.xml:
          hbase.rest.threads.min: "4"
        hbase-env.sh:
          HBASE_HEAPSIZE: "2G"
      replicas: 1
----

Just as for the `config`, it is possible to specify this at role level as well:

[source,yaml]
----
restServers:
  configOverrides:
    hbase-site.xml:
      hbase.rest.threads.min: "4"
    hbase-env.sh:
      HBASE_HEAPSIZE: "2G"
  roleGroups:
    default:
      config: {}
      replicas: 1
----

All override property values must be strings. The properties will be formatted and escaped correctly into the XML file, respectively inserted as is into the `env.sh` file.

For a full list of configuration options we refer to the HBase https://hbase.apache.org/book.html#config.files[Configuration Documentation].

// Environment configuration is not implemented. The environment is managed
// with the hbase-env.sh configuration file

// CLI overrides are also not implemented
