= Usage

After installation, the CRD for this operator must be created:

    kubectl apply -f /etc/stackable/hbase-operator/crd/hbasecluster.crd.yaml

The Stackable Operator for Apache HBase requires an active Apache ZooKeeper installation provided by Stackable to be present.

The Stackable Operator for Apache HBase requires an active Apache HDFS installation provided by Stackable to be present.

To create a single node Apache HBase (v2.4.6) cluster with Prometheus metrics exposed on port 9505 (master) and 9506 (region_server):

    cat <<EOF | kubectl apply -f -
    apiVersion: hbase.stackable.tech/v1alpha1
    kind: HbaseCluster
    metadata:
      name: simple
    spec:
      version: 2.4.6
      hdfsReference:
        namespace: default
        name: simple
        root: /hbase
      zookeeperReference:
        namespace: default
        name: simple
      masters:
        roleGroups:
          default:
            selector:
              matchLabels:
                kubernetes.io/os: linux
            replicas: 1
            config:
              masterWebUiPort: 17000
              metricsPort: 9707
      regionServers:
        roleGroups:
          default:
            selector:
              matchLabels:
                kubernetes.io/os: linux
            replicas: 1
            config:
              regionServerWebUiPort: 17001
              metricsPort: 9708
    EOF

If you set up an HBase service for the first time, you might need to create the `/hbase` folder after the pods are created:

    export HADOOP_USER_NAME=root
    ./hdfs dfs -mkdir hdfs://<namenode>:9000/hbase
    ./hdfs dfs -chown stackable hdfs://<namenode>:9000/hbase

