= Usage

== Requirements

A distributed Apache HBase installation depends on a running Apache ZooKeeper and HDFS cluster. See
the documentation for the https://docs.stackable.tech/hdfs/usage.html[Stackable Operator for Apache HDFS]
how to set up these clusters.

== Deployment of an Apache HBase cluster

An Apache HBase cluster can be created with the following cluster specification:

[source,yaml]
----
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: simple
spec:
  version: 2.4.6
  config:
    hdfsConfigMapName: simple-namenode-default
    zookeeperConfigMapName: simple-znode
    hbaseManagesZk: false
    hbaseClusterDistributed: true
    hbaseRootdir: hdfs://simple/hbase
  masters:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
  regionServers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
  restServers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
----

`hdfsConfigMapName` references the config map created by the Stackable HDFS operator.

`zookeeperConfigMapName` references the config map created by the Stackable ZooKeeper operator.

`hbaseManagesZk` is mapped to the environment variable `HBASE_MANAGES_ZK` in `hbase-env.sh`.

`hbaseClusterDistributed` is mapped to `hbase.cluster.distributed` in `hbase-site.xml`.

`hbaseRootdir` is mapped to `hbase.rootdir` in `hbase-site.xml`.
