apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: simple
spec:
  version: 2.4.6
  masters:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/arch: stackable-linux
  regionServers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/arch: stackable-linux




