apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: simple
spec:
  version: 2.4.6
  config:
    hdfsConfigMapName: simple-namenode-default
    zookeeperConfigMapName: simple-znode
    hbaseManagesZk: false
    hbaseClusterDistributed: true
    hbaseRootdir: hdfs://simple/hbase
  masters:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
  regionServers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
  restServers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
