---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: hcloud-centos-8
metadata:
  name: hbase-operator-integration-tests
  description: "Cluster for HBase Operator Integration Tests (Hetzner Cloud / CentOS 8)"
domain: stackable.test
publicKeys: []
spec:
  location: "hel1"
  k8sVersion: "$K8S_VERSION"
  wireguard: false
  versions:
    _-operator: NIGHTLY
    hbase-operator: "$HBASE_OPERATOR_VERSION"
  nodes:
    main:
      numberOfNodes: 3
