---
apiVersion: batch/v1
kind: Job
metadata:
  name: hbck2-recover-unknown
spec:
  template:
    spec:
      containers:
      - name: hbck2
        image: oci.stackable.tech/sdp/hbase:2.6.3-stackable25.11.0
        volumeMounts:
        - name: hbase-config
          mountPath: /stackable/conf
        env:
        - name: HBASE_CONF_DIR
          value: /stackable/conf
        - name: HADOOP_CONF_DIR
          value: /stackable/conf
        command:
        - hbck2
        args:
        - recoverUnknown
      volumes:
      - name: hbase-config
        projected:
          sources:
          - configMap:
              name: simple-hdfs
          - configMap:
              name: simple-hbase-master-default
