---
apiVersion: batch/v1
kind: Job
metadata:
  name: export-hbase-snapshot
spec:
  template:
    spec:
      containers:
      - name: hbase
        image: oci.stackable.tech/sdp/hbase:2.6.3-stackable0.0.0-dev
        volumeMounts:
        - name: hbase-config
          mountPath: /stackable/conf
        env:
        - name: HBASE_CONF_DIR
          value: /stackable/conf
        - name: HADOOP_CONF_DIR
          value: /stackable/conf
        - name: AWS_ENDPOINT
          value: https://s3endpoint:9000/
        - name: AWS_SSL_ENABLED
          value: true
        - name: AWS_PATH_STYLE_ACCESS
          value: true
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access-key-id
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret-key
        command:
        - export-snapshot-to-s3
        args:
        - --snapshot
        - my-snapshot
        - --copy-to
        - s3a://hbase/my-snapshot
        - --no-checksum-verify
      volumes:
      - name: hbase-config
        projected:
          sources:
          - configMap:
              name: simple-hdfs
          - configMap:
              name: simple-hbase-master-default
      restartPolicy: Never
